# Generated by Django 4.0.6 on 2022-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
