# Generated by Django 4.0.6 on 2022-08-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_organisation_role_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
