# Generated by Django 4.0.6 on 2022-08-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_users_options_remove_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ManyToManyField(to='base.role'),
        ),
    ]
