# Generated by Django 4.0.6 on 2022-08-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Organisation',
        ),
        migrations.AddField(
            model_name='users',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.organisation'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('QA', 'QA'), ('Manager', 'Manager'), ('Team Lead', 'Team Lead')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
