# Generated by Django 4.0.6 on 2022-08-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_users_role_organisation_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='organisation',
        ),
        migrations.AddField(
            model_name='organisation',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.users'),
        ),
    ]
