# Generated by Django 4.0.6 on 2022-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_organisation_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='organisation',
            field=models.ManyToManyField(to='base.organisation'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ManyToManyField(default='Developer', to='base.role'),
        ),
    ]
