# Generated by Django 4.0.6 on 2022-08-17 12:05

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_role_users_organisation_remove_users_role_users_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='date_created',
        ),
        migrations.AddField(
            model_name='organisation',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
