# Generated by Django 4.0.6 on 2022-08-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_users_role_users_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
