# Generated by Django 4.0.6 on 2022-08-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='organisation',
        ),
        migrations.AddField(
            model_name='users',
            name='organisation',
            field=models.ManyToManyField(to='base.organisation'),
        ),
    ]
