# Generated by Django 4.0.6 on 2022-08-17 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_users_role_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userorg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('role', models.CharField(choices=[('Develpoer', 'Developer'), ('Tester', 'Tester'), ('QA', 'QA'), ('Manager', 'Manager'), ('Team Lead', 'Team Lead')], default='Developer', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Userorg',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='organisation',
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'organisation'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ManyToManyField(related_name='user_orgnization', through='base.Userorg', to='base.organisation'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='userorg',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organisation'),
        ),
        migrations.AddField(
            model_name='userorg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
